@extends('layouts.admin')
@section('title', 'Kelola Guru & Staff')
@section('content')
<style>
.teacher-photo {width:70px;height:70px;object-fit:cover;border-radius:10px;box-shadow:0 2px 6px rgba(0,0,0,0.1);}
.teacher-photo-lg {width:140px;height:140px;object-fit:cover;border-radius:15px;box-shadow:0 3px 10px rgba(0,0,0,0.15);display:block;margin:0 auto;}
.preview-info p {margin-bottom:6px;}
</style>
<div class="container-fluid px-4">
<div class="d-flex justify-content-between align-items-center mb-3">
<h5 class="text-primary fw-bold"><i class="fas fa-users"></i> Kelola Guru & Staff</h5>
<button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#addModal"><i class="fas fa-plus-circle"></i> Tambah</button>
</div>
<div class="row mb-4">
<div class="col-xl-3 col-md-6 mb-3"><div class="card border-left-danger shadow h-100 py-2"><div class="card-body d-flex justify-content-between align-items-center"><div><div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Kepala Sekolah</div><div class="h5 mb-0 font-weight-bold text-gray-800">{{$count_principal}}</div></div><i class="fas fa-crown fa-2x text-gray-300"></i></div></div></div>
<div class="col-xl-3 col-md-6 mb-3"><div class="card border-left-primary shadow h-100 py-2"><div class="card-body d-flex justify-content-between align-items-center"><div><div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Guru</div><div class="h5 mb-0 font-weight-bold text-gray-800">{{$count_teacher}}</div></div><i class="fas fa-chalkboard-teacher fa-2x text-gray-300"></i></div></div></div>
<div class="col-xl-3 col-md-6 mb-3"><div class="card border-left-success shadow h-100 py-2"><div class="card-body d-flex justify-content-between align-items-center"><div><div class="text-xs font-weight-bold text-success text-uppercase mb-1">Staff</div><div class="h5 mb-0 font-weight-bold text-gray-800">{{$count_staff}}</div></div><i class="fas fa-user-tie fa-2x text-gray-300"></i></div></div></div>
<div class="col-xl-3 col-md-6 mb-3"><div class="card border-left-info shadow h-100 py-2"><div class="card-body d-flex justify-content-between align-items-center"><div><div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total</div><div class="h5 mb-0 font-weight-bold text-gray-800">{{$count_total}}</div></div><i class="fas fa-users fa-2x text-gray-300"></i></div></div></div>
</div>
<div class="card border-0 shadow-sm rounded-4"><div class="card-body p-3"><div class="table-responsive"><table class="table table-hover align-middle table-sm text-center"><thead class="table-light"><tr><th>No</th><th>Foto</th><th>Nama</th><th>Kategori</th><th>Jabatan</th><th>Kualifikasi</th><th>Email</th><th>Telepon</th><th>Aksi</th></tr></thead><tbody>@if($teachers->isEmpty())<tr><td colspan="9" class="text-muted py-3">Belum ada data</td></tr>@else @foreach($teachers as $no=>$t)<tr><td>{{$no+1}}</td><td>@if($t->photo && file_exists(public_path('assets/img/teachers/'.$t->photo)))<img src="{{asset('assets/img/teachers/'.$t->photo)}}" class="teacher-photo">@else<span class="text-muted small fst-italic">Tidak ada</span>@endif</td><td>{{$t->name}}</td><td>{{ucfirst($t->category)}}</td><td>{{$t->position}}</td><td>{{$t->qualifications}}</td><td>{{$t->email}}</td><td>{{$t->phone}}</td><td><div class="d-flex justify-content-center gap-1 flex-wrap"><button class="btn btn-sm btn-warning btn-edit" data-id="{{$t->id}}" data-name="{{$t->name}}" data-position="{{$t->position}}" data-qualifications="{{$t->qualifications}}" data-experience="{{$t->experience}}" data-email="{{$t->email}}" data-phone="{{$t->phone}}" data-category="{{$t->category}}" data-photo="{{$t->photo}}"><i class="fas fa-edit"></i></button><button class="btn btn-sm btn-info text-white btn-preview" data-name="{{$t->name}}" data-position="{{$t->position}}" data-qualifications="{{$t->qualifications}}" data-experience="{{$t->experience}}" data-email="{{$t->email}}" data-phone="{{$t->phone}}" data-category="{{$t->category}}" data-photo="{{$t->photo}}"><i class="fas fa-eye"></i></button><form action="{{route('admin.guru.destroy',$t->id)}}" method="POST" style="display:inline"><input type="hidden" name="_token" value="{{csrf_token()}}"><input type="hidden" name="_method" value="DELETE"><button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Hapus data ini?')"><i class="fas fa-trash"></i></button></form></div></td></tr>@endforeach @endif</tbody></table></div></div></div>
</div>
<div class="modal fade" id="addModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form method="post" action="{{route('admin.guru.store')}}" enctype="multipart/form-data"><input type="hidden" name="_token" value="{{csrf_token()}}"><div class="modal-header bg-primary text-white py-2"><h6 class="modal-title">Tambah Guru / Staff</h6><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-md-6"><label>Nama</label><input type="text" name="name" class="form-control" required></div><div class="col-md-6"><label>Jabatan</label><input type="text" name="position" class="form-control"></div><div class="col-md-6"><label>Kualifikasi</label><input type="text" name="qualifications" class="form-control"></div><div class="col-md-6"><label>Pengalaman</label><input type="text" name="experience" class="form-control"></div><div class="col-md-6"><label>Email</label><input type="email" name="email" class="form-control"></div><div class="col-md-6"><label>Telepon</label><input type="text" name="phone" class="form-control"></div><div class="col-md-6"><label>Kategori</label><select name="category" class="form-select"><option value="teacher">Guru</option><option value="staff">Staff</option><option value="principal">Kepala Sekolah</option></select></div><div class="col-md-6"><label>Foto</label><input type="file" name="photo" class="form-control"></div></div><div class="modal-footer py-2"><button type="submit" class="btn btn-primary btn-sm">Simpan</button></div></form></div></div></div>
<div class="modal fade" id="editModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form method="post" action="" id="editForm" enctype="multipart/form-data"><input type="hidden" name="_token" value="{{csrf_token()}}"><input type="hidden" name="_method" value="PUT"><input type="hidden" name="id" id="edit-id"><div class="modal-header bg-warning text-white py-2"><h6 class="modal-title">Edit Data</h6><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-md-6"><label>Nama</label><input type="text" name="name" id="edit-name" class="form-control"></div><div class="col-md-6"><label>Jabatan</label><input type="text" name="position" id="edit-position" class="form-control"></div><div class="col-md-6"><label>Kualifikasi</label><input type="text" name="qualifications" id="edit-qualifications" class="form-control"></div><div class="col-md-6"><label>Pengalaman</label><input type="text" name="experience" id="edit-experience" class="form-control"></div><div class="col-md-6"><label>Email</label><input type="email" name="email" id="edit-email" class="form-control"></div><div class="col-md-6"><label>Telepon</label><input type="text" name="phone" id="edit-phone" class="form-control"></div><div class="col-md-6"><label>Kategori</label><select name="category" id="edit-category" class="form-select"><option value="teacher">Guru</option><option value="staff">Staff</option><option value="principal">Kepala Sekolah</option></select></div><div class="col-md-6"><label>Foto</label><input type="file" name="photo" class="form-control"><div id="edit-photo-preview" class="mt-2 text-center"></div></div></div><div class="modal-footer py-2"><button type="submit" class="btn btn-warning btn-sm">Update</button></div></form></div></div></div>
<div class="modal fade" id="previewModal" tabindex="-1"><div class="modal-dialog modal-md modal-dialog-centered"><div class="modal-content"><div class="modal-header bg-info text-white py-2"><h6 class="modal-title">Detail Guru / Staff</h6><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body text-center" id="preview-body"></div></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script>
$(document).ready(function(){$('.table').DataTable({language:{url:'https://cdn.datatables.net/plug-ins/1.13.6/i18n/id.json'},pageLength:10,order:[[0,'asc']]});});
@if(session('success'))Swal.fire({icon:'success',title:'{{session('success')}}',showConfirmButton:false,timer:1200});@endif
document.querySelectorAll('.btn-edit').forEach(btn=>{btn.addEventListener('click',()=>{const id=btn.dataset.id;document.getElementById('edit-id').value=id;document.getElementById('editForm').action='/admin/guru/'+id;document.getElementById('edit-name').value=btn.dataset.name;document.getElementById('edit-position').value=btn.dataset.position;document.getElementById('edit-qualifications').value=btn.dataset.qualifications;document.getElementById('edit-experience').value=btn.dataset.experience;document.getElementById('edit-email').value=btn.dataset.email;document.getElementById('edit-phone').value=btn.dataset.phone;document.getElementById('edit-category').value=btn.dataset.category;const p=document.getElementById('edit-photo-preview');p.innerHTML=btn.dataset.photo?`<img src="/assets/img/teachers/${btn.dataset.photo}" class="teacher-photo-lg">`:`<span class="text-muted small fst-italic">Tidak ada foto</span>`;new bootstrap.Modal(document.getElementById('editModal')).show();});});
document.querySelectorAll('.btn-preview').forEach(btn=>{btn.addEventListener('click',()=>{const img=btn.dataset.photo?`<img src="/assets/img/teachers/${btn.dataset.photo}" class="teacher-photo-lg mb-3">`:`<div class="text-muted small mb-2 fst-italic">Tidak ada foto</div>`;const html=`${img}<h6 class="fw-bold mb-1">${btn.dataset.name}</h6><p class="text-muted mb-1">${btn.dataset.position||'-'}</p><p class="small mb-1"><b>Kualifikasi:</b> ${btn.dataset.qualifications||'-'}</p><p class="small mb-1"><b>Pengalaman:</b> ${btn.dataset.experience||'-'}</p><p class="small mb-1"><b>Email:</b> ${btn.dataset.email||'-'}</p><p class="small mb-1"><b>Telepon:</b> ${btn.dataset.phone||'-'}</p><p class="small"><b>Kategori:</b> ${btn.dataset.category}</p>`;document.getElementById('preview-body').innerHTML=html;new bootstrap.Modal(document.getElementById('previewModal')).show();});});
</script>
@endsection